### ISSUE TITLE
Default admin user?

### ISSUE THREAD

**Issue by seitzbg** [ngoduykhanh/PowerDNS-Admin#11]
When I try to sign up I get:

(_mysql_exceptions.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`powerdnsadmin`.`user`, CONSTRAINT `user_ibfk_1` FOREIGN KEY (`role_id`) REFERENCES `role` (`id`))') [SQL: u'INSERT INTO user (username, password, firstname, lastname, email, avatar, role_id) VALUES (%s, %s, %s, %s, %s, %s, %s)'] [parameters: ('bryan_seitz', 'hash was here, 'Bryan', 'Seitz', 'bryan_seitz@host.com, None, 1)] 

Is there a default admin user ?

**Comment by seitzbg** [comment]
I fixed the SQL issue, my DB is a cluster so auto increment is not equal to 1.  You might want to populate the initial data for roles with the create script and enter values manually and or search for the role name when adding a user.  Also can you add the ability do disable signup with regular auth ? Another thing that would be nice is to enforce an LDAP group membership as well.

**Comment by ivanfilippov** [comment]
Hi @seitzbg!

I ran into the same issue with my SQL cluster and it looks to be a simple fix. You can grab the modified branch [here](https://github.com/ivanfilippov/PowerDNS-Admin/tree/db_improvements) if you'd like to try it out. These changes automate the population of the Administrator and User roles and also search for the role names/IDs instead of expecting them to be specific values.

I'll be submitting a pull request for @ngoduykhanh as well, so hopefully this will make it into the main code as well. :smile:

**Comment by ivanfilippov** [comment]
Hi @seitzbg!

I've added initial support for LDAP group membership (although I've only tested it with an AD style LDAP). Please try the branch [here](https://github.com/ivanfilippov/PowerDNS-Admin/tree/ldap_group_security) and provide feedback if you have any.

@ngoduykhanh please review the initial implementation of this branch.

**Comment by ngoduykhanh** [comment]
Thank you @ivanfilippov  for your help. I've tried your branch `db_improments`. It works fine for me. You can submit a pull request for it 👍 .

About LDAP group membership, I have no idea why do we need it since we are managing the user privileges/role via PowerDNS-Admin itself. And the filter `(&(objectcategory=group)(member=%s))` seems doesn't work all cases, at least for me, maybe :)

**Comment by ivanfilippov** [comment]
Thanks for accepting the PR @ngoduykhanh!

I think the primary reason @seitzbg mentioned the LDAP group enforcement is to prevent users creating "empty" accounts in the PowerDNS-Admin database.  I could be wrong, hopefully @seitzbg will let us know.

I took it a bit further than that and allowed the management of normal users and admin users via AD groups instead of PowerDNS-Admin itself. I left the option to the user (via the `LDAP_GROUP_SECURITY` config option) as to whether they want to manage their admins/users via PowerDNS-Admin directly or via LDAP. I'm not married to the implementation though (and I don't personally use the current LDAP functionality and most likely will not in the future) so if @seitzbg and you don't see a fit for it, I'm ok to let it go.

Just out of curiosity, what type of LDAP did you test against? This is my first try at writing code that talks to LDAP so I'm interested in what could break it. I used a Windows Server 2012 R2 domain controller running at a 2012 R2 domain functional level and didn't find any issues (I only tested for an hour or two with only a few test users, so I might have missed something).

**Comment by ngoduykhanh** [comment]
Hi @ivanfilippov ,

I am using openLDAP on Linux which may has diffrence schema. I've not tried it on Windows Server yet. If we decide to have this feature I can help to take a look deeper :)

You put `LDAP_GROUP_SECURITY ` to be able to switch on/off this feature, it is good. I just have one sugesstion, if `LDAP_GROUP_SECURITY` is `False`, we shouldn't force to the value of `LDAP_ADMIN_GROUP` and `LDAP_USER_GROUP` [like this](https://github.com/ivanfilippov/PowerDNS-Admin/blob/d417cfb8dc2584940420e28dffce196addfc6d17/app/models.py#L23), so people doesn't need to configure them in the config file.

**Comment by ivanfilippov** [comment]
Good idea! I've moved those two behind a condition in models.py

Is your LDAP_TYPE set to 'ldap' or 'ad'? I'll set up an openLDAP server as well so I can test against both.

**Comment by ngoduykhanh** [comment]
@ivanfilippov : My `LDAP_TYPE` is `ldap`:)

**Comment by ivanfilippov** [comment]
The main issue is now fixed in `master` with the merging of #18 that includes the following commit: https://github.com/ivanfilippov/PowerDNS-Admin/commit/64531999f655d7317efd74eda9cd20d9d06b0b18

The LDAP group based security discussion is unrelated to the issue title so I recommend this issue be closed.
