### ISSUE TITLE
cp: cannot stat ‘/home/web/powerdns-admin/config_template_docker.py’: No such file or directory

### ISSUE THREAD

**Issue by harobed** [ngoduykhanh/PowerDNS-Admin#134]
```
docker-compose logs -f powerdns-admin
Attaching to powerdnsadmin_powerdns-admin_1
powerdns-admin_1                  | cp: cannot stat ‘/home/web/powerdns-admin/config_template_docker.py’: No such file or directory
powerdns-admin_1                  | cp: cannot stat ‘/home/web/powerdns-admin/config_template_docker.py’: No such file or directory
powerdnsadmin_powerdns-admin_1 exited with code 1
```

**Comment by jallakim** [comment]
Uhm, is this the latest version from git? The file it complains about was removed in commit [0c94d3b](https://github.com/ngoduykhanh/PowerDNS-Admin/commit/0c94d3b80cee7a693c9d66828cb60af824221a39). Not sure how docker works if you ran docker *before* the file was removed (so that it expects it to be there), and then update from git, and run docker again.

If it's a clean install, there's no reference to that file anywhere in the code as far as I can see....

**Comment by harobed** [comment]
I did:

```
$ git clone https://github.com/ngoduykhanh/PowerDNS-Admin.git .
$ docker-compose up
```

**Comment by harobed** [comment]
#135
