### ISSUE TITLE
400  Oops! Bad request The server refused to process your request and return a 400 error.

### ISSUE THREAD

**Issue by jeromeza** [ngoduykhanh/PowerDNS-Admin#153]
# 
# ADDING A DOMAIN

400
 Oops! Bad request
The server refused to process your request and return a 400 error. You may return to the dashboard.

This error is seen when adding a new domain. Fresh Ubuntu 16.04 install with MariaDB as the backend (no master slave setup - single server).
# 
# POWERDNS VERSION

$pdns_control 
version 4.0.1
# 
# OS RELEASE INFO

$cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
# 
# PowerDNS-Admin Log

[ERROR] Cannot add domain yolo.co.za.
[DEBUG] While fetching http://localhost:8081/api/v1/servers/localhost/zones: 500 Server Error: Internal Server Error
# 
# PDNS.CONF

api=yes
api-key=1343324
webserver=yes
webserver-address=127.0.0.1
webserver-port=8081
# 

Curl to show its working:

curl http://localhost:8081 | grep PowerDNS
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
<title>PowerDNS Authoritative Server Monitor</title>

<div class="headl columns"><a href="/" id="appname">PowerDNS 4.0.1</a></div>

100 13228  100 13228    0     0  1228k      0 --:--:-- --:--:-- --:--:-- 1291k
<footer class="row">PowerDNS Authoritative Server 4.0.1 (built Jul 29 2016 15:56:40 by root@350bdb04f2b1)<br>&copy; 2013 - 2016 <a href="http://www.powerdns.com/">PowerDNS.COM BV</a>.</footer>
# 
# CONFIG.PY

POWERDNS CONFIG
PDNS_STATS_URL = 'http://127.0.0.1:8081/'
PDNS_API_KEY = '1343324'
PDNS_VERSION = '4.0.1'

**Comment by ngoduykhanh** [comment]
Can you create a domain via curl to the powerdns api?
https://doc.powerdns.com/md/httpapi/api_spec/#url-apiv1serversserver95idzones

**Comment by jeromeza** [comment]
Hi,

Unfortunately I moved on to another frontend in the interim so I can't test again.

**Comment by METAJIJI** [comment]
Seems database backend is not installed!

Read the oficial docs: https://doc.powerdns.com/md/httpapi/README/

> Try it
> Install PowerDNS Authoritative with one of the gsql backends (i.e. MySQL, PostgreSQL or SQLite3).
> 

For `sqlite3` example on **Ubuntu 14.04**:
```
curl -sS https://repo.powerdns.com/FD380FBB-pub.asc | apt-key add -
cat >/etc/apt/sources.list.d/pdns.list<<_EOF
deb [arch=amd64] http://repo.powerdns.com/ubuntu trusty-auth-40 main
deb [arch=amd64] http://repo.powerdns.com/ubuntu trusty-rec-40 main
_EOF

apt update

apt install -y sqlite3 pdns-server pdns-backend-sqlite3
install -o pdns -g pdns -d /var/lib/powerdns/db
sudo -u pdns -H sqlite3 /var/lib/powerdns/db/pdns.sqlite3 < /usr/share/doc/pdns-backend-sqlite3/schema.sqlite3.sql
sed 's|\(gsqlite3-database=\).*|\1/var/lib/powerdns/db/pdns.sqlite3|g' /usr/share/pdns-backend-sqlite3/pdns.local.gsqlite3.conf >> /etc/powerdns/pdns.d/pdns.local.conf

service pdns restart
```

**Comment by jallakim** [comment]
@jeromeza or @ngoduykhanh; close this issue, maybe?

**Comment by ivanfilippov** [comment]
Original issue requestor is not longer using PDNS-A. Closing.

**Comment by dastrath** [comment]
Had the same issue.

Solved it by

(a) activating the api
(b) using the correct pdns-version in PowerDNS-Admin-config file

**Comment by kvanleeuwen** [comment]
Hello,

I also get this message, when I check the logs I see:

Jul  8 13:36:03 template gunicorn[22518]: [2019-07-08 13:36:03,713] [DEBUG] | Starting new HTTP connection (1): (location):80
Jul  8 13:36:03 template gunicorn[22518]: [2019-07-08 13:36:03,726] [ERROR] | Cannot add domain testdomein.nl.
Jul  8 13:36:03 template gunicorn[22518]: [2019-07-08 13:36:03,727] [DEBUG] | Traceback (most recent call last):
Jul  8 13:36:03 template gunicorn[22518]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
Jul  8 13:36:03 template gunicorn[22518]:     chunked=chunked)
Jul  8 13:36:03 template gunicorn[22518]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
Jul  8 13:36:03 template gunicorn[22518]:     six.raise_from(e, None)
Jul  8 13:36:03 template gunicorn[22518]:   File "<string>", line 2, in raise_from
Jul  8 13:36:03 template gunicorn[22518]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
Jul  8 13:36:03 template gunicorn[22518]:     httplib_response = conn.getresponse()
Jul  8 13:36:03 template gunicorn[22518]:   File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
Jul  8 13:36:03 template gunicorn[22518]:     response.begin()
Jul  8 13:36:03 template gunicorn[22518]:   File "/usr/lib/python3.6/http/client.py", line 297, in begin
Jul  8 13:36:03 template gunicorn[22518]:     version, status, reason = self._read_status()
Jul  8 13:36:03 template gunicorn[22518]:   File "/usr/lib/python3.6/http/client.py", line 285, in _read_status
Jul  8 13:36:03 template gunicorn[22518]:     raise BadStatusLine(line)
Jul  8 13:36:03 template gunicorn[22518]: http.client.BadStatusLine: HTTP/1.0 1005 UNKNOWN
Jul  8 13:36:03 template gunicorn[22518]: During handling of the above exception, another exception occurred:
Jul  8 13:36:03 template gunicorn[22518]: Traceback (most recent call last):
Jul  8 13:36:03 template gunicorn[22518]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
Jul  8 13:36:03 template gunicorn[22518]:     timeout=timeout
Jul  8 13:36:03 template gunicorn[22518]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
Jul  8 13:36:03 template gunicorn[22518]:     _stacktrace=sys.exc_info()[2])
Jul  8 13:36:03 template gunicorn[22518]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/urllib3/util/retry.py", line 368, in increment
Jul  8 13:36:03 template gunicorn[22518]:     raise six.reraise(type(error), error, _stacktrace)
Jul  8 13:36:03 template gunicorn[22518]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
Jul  8 13:36:03 template gunicorn[22518]:     raise value.with_traceback(tb)
Jul  8 13:36:03 template gunicorn[22518]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
Jul  8 13:36:03 template gunicorn[22518]:     chunked=chunked)
Jul  8 13:36:03 template gunicorn[22518]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
Jul  8 13:36:03 template gunicorn[22518]:     six.raise_from(e, None)
Jul  8 13:36:03 template gunicorn[22518]:   File "<string>", line 2, in raise_from
Jul  8 13:36:03 template gunicorn[22518]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
Jul  8 13:36:03 template gunicorn[22518]:     httplib_response = conn.getresponse()
Jul  8 13:36:03 template gunicorn[22518]:   File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
Jul  8 13:36:03 template gunicorn[22518]:     response.begin()
Jul  8 13:36:03 template gunicorn[22518]:   File "/usr/lib/python3.6/http/client.py", line 297, in begin
Jul  8 13:36:03 template gunicorn[22518]:     version, status, reason = self._read_status()
Jul  8 13:36:03 template gunicorn[22518]:   File "/usr/lib/python3.6/http/client.py", line 285, in _read_status
Jul  8 13:36:03 template gunicorn[22518]:     raise BadStatusLine(line)
Jul  8 13:36:03 template gunicorn[22518]: urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine('HTTP/1.0 1005 UNKNOWN\r\n',))
Jul  8 13:36:03 template gunicorn[22518]: During handling of the above exception, another exception occurred:
Jul  8 13:36:03 template gunicorn[22518]: Traceback (most recent call last):
Jul  8 13:36:03 template gunicorn[22518]:   File "/opt/web/powerdns-admin/app/models.py", line 1023, in add
Jul  8 13:36:03 template gunicorn[22518]:     urljoin(self.PDNS_STATS_URL, self.API_EXTENDED_URL + '/servers/localhost/zones'), headers=headers, method='POST', data=post_data)
Jul  8 13:36:03 template gunicorn[22518]:   File "/opt/web/powerdns-admin/app/lib/utils.py", line 115, in fetch_json
Jul  8 13:36:03 template gunicorn[22518]:     accept='application/json; q=1')
Jul  8 13:36:03 template gunicorn[22518]:   File "/opt/web/powerdns-admin/app/lib/utils.py", line 100, in fetch_remote
Jul  8 13:36:03 template gunicorn[22518]:     params=params
Jul  8 13:36:03 template gunicorn[22518]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/requests/api.py", line 60, in request
Jul  8 13:36:03 template gunicorn[22518]:     return session.request(method=method, url=url, **kwargs)
Jul  8 13:36:03 template gunicorn[22518]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/requests/sessions.py", line 524, in request
Jul  8 13:36:03 template gunicorn[22518]:     resp = self.send(prep, **send_kwargs)
Jul  8 13:36:03 template gunicorn[22518]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/requests/sessions.py", line 637, in send
Jul  8 13:36:03 template gunicorn[22518]:     r = adapter.send(request, **kwargs)
Jul  8 13:36:03 template gunicorn[22518]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
Jul  8 13:36:03 template gunicorn[22518]:     raise ConnectionError(err, request=request)
Jul  8 13:36:03 template gunicorn[22518]: requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('HTTP/1.0 1005 UNKNOWN\r\n',))

I don't get this, because the admin panel works fine (I can create users, change settings etc.), but when I try to create a domain, it fails. I checked the version of pdns and copy/pasted that in the API pdns settings field (4.1.1.) and I've set the api key in the database. So does someone know what goes wrong?

Thanks in advance and regards

**Comment by chandertechavidity** [comment]
I am also getting the similar error.

Ubuntu 18 Bionic LTS
PowerDNS: 4.1.1
Backend: Postgresql

When i try to get create new domain, got 400 in the console, from syslog, i am getting the following error.

Jul 28 21:33:46 tadns gunicorn[911]:     apikey_val = str(base64.b64decode(auth_header), 'utf-8')
Jul 28 21:33:46 tadns gunicorn[911]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9f in position 3: invalid start byte
Jul 28 21:33:46 tadns gunicorn[911]: [2019-07-28 21:33:46,384] [DEBUG] | http://tadns.techavidity.com:80 "GET /api/v1/servers/localhost/zones HTTP/1.1" 500 32
Jul 28 21:33:46 tadns gunicorn[911]: [2019-07-28 21:33:46,385] [ERROR] | Returned status 500 and content b'{"msg": "Internal Server Error"}'
Jul 28 21:33:46 tadns gunicorn[911]: [2019-07-28 21:33:46,385] [ERROR] | Can not update domain table. Error: Error while fetching http://tadns.techavidity.com/api/v1/servers/localhost/zones
Jul 28 21:33:46 tadns gunicorn[911]: [2019-07-28 21:33:46,401] [DEBUG] | Starting new HTTP connection (1): tadns.techavidity.com:80
Jul 28 21:33:46 tadns gunicorn[911]: [2019-07-28 21:33:46,409] [ERROR] | Exception on /api/v1/servers/localhost/statistics [GET]
Jul 28 21:33:46 tadns gunicorn[911]: Traceback (most recent call last):
Jul 28 21:33:46 tadns gunicorn[911]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
Jul 28 21:33:46 tadns gunicorn[911]:     response = self.full_dispatch_request()
Jul 28 21:33:46 tadns gunicorn[911]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
Jul 28 21:33:46 tadns gunicorn[911]:     rv = self.handle_user_exception(e)
Jul 28 21:33:46 tadns gunicorn[911]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
Jul 28 21:33:46 tadns gunicorn[911]:     reraise(exc_type, exc_value, tb)
Jul 28 21:33:46 tadns gunicorn[911]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
Jul 28 21:33:46 tadns gunicorn[911]:     raise value
Jul 28 21:33:46 tadns gunicorn[911]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
Jul 28 21:33:46 tadns gunicorn[911]:     rv = self.dispatch_request()
Jul 28 21:33:46 tadns gunicorn[911]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
Jul 28 21:33:46 tadns gunicorn[911]:     return self.view_functions[rule.endpoint](**req.view_args)
Jul 28 21:33:46 tadns gunicorn[911]:   File "/opt/web/powerdns-admin/app/decorators.py", line 191, in decorated_function
Jul 28 21:33:46 tadns gunicorn[911]:     apikey_val = str(base64.b64decode(auth_header), 'utf-8')
Jul 28 21:33:46 tadns gunicorn[911]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9f in position 3: invalid start byte
Jul 28 21:33:46 tadns gunicorn[911]: [2019-07-28 21:33:46,415] [DEBUG] | http://tadns.techavidity.com:80 "GET /api/v1/servers/localhost/statistics HTTP/1.1" 500 32
Jul 28 21:33:46 tadns gunicorn[911]: [2019-07-28 21:33:46,417] [ERROR] | Returned status 500 and content b'{"msg": "Internal Server Error"}'
Jul 28 21:33:46 tadns gunicorn[911]: [2019-07-28 21:33:46,417] [ERROR] | Can not get server statistics. DETAIL: Error while fetching http://tadns.techavidity.com/api/v1/servers/localhost/statistics
Jul 28 21:33:46 tadns gunicorn[911]: [2019-07-28 21:33:46,418] [DEBUG] | Traceback (most recent call last):
Jul 28 21:33:46 tadns gunicorn[911]:   File "/opt/web/powerdns-admin/app/lib/utils.py", line 104, in fetch_remote
Jul 28 21:33:46 tadns gunicorn[911]:     r.raise_for_status()
Jul 28 21:33:46 tadns gunicorn[911]:   File "/opt/web/powerdns-admin/flask/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
Jul 28 21:33:46 tadns gunicorn[911]:     raise HTTPError(http_error_msg, response=self)
Jul 28 21:33:46 tadns gunicorn[911]: requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://tadns.techavidity.com/api/v1/servers/localhost/statistics
Jul 28 21:33:46 tadns gunicorn[911]: During handling of the above exception, another exception occurred:
Jul 28 21:33:46 tadns gunicorn[911]: Traceback (most recent call last):
Jul 28 21:33:46 tadns gunicorn[911]:   File "/opt/web/powerdns-admin/app/models.py", line 1934, in get_statistic
Jul 28 21:33:46 tadns gunicorn[911]:     urljoin(self.PDNS_STATS_URL, self.API_EXTENDED_URL + '/servers/{0}/statistics'.format(self.server_id)), headers=headers, method='GET')
Jul 28 21:33:46 tadns gunicorn[911]:   File "/opt/web/powerdns-admin/app/lib/utils.py", line 115, in fetch_json
Jul 28 21:33:46 tadns gunicorn[911]:     accept='application/json; q=1')
Jul 28 21:33:46 tadns gunicorn[911]:   File "/opt/web/powerdns-admin/app/lib/utils.py", line 108, in fetch_remote
Jul 28 21:33:46 tadns gunicorn[911]:     raise RuntimeError('Error while fetching {0}'.format(remote_url))
Jul 28 21:33:46 tadns gunicorn[911]: RuntimeError: Error while fetching http://tadns.techavidity.com/api/v1/servers/localhost/statistics

**Comment by abhichatur** [comment]
Solved it by putting the value in pdns.conf
webserver-address=127.0.0.1
webserver-port=8081

and in the poweradmin panel same address and port should be given,  you can also check the pdns version using following command 
 pdns_control version

this version you need to mention in poweradmin panel.

then check with this, it will show the connectivity:
 curl http://localhost:8081 | grep PowerDNS
