### ISSUE TITLE
Docker + Docker Compose example

### ISSUE THREAD

**Issue by almereyda** [ngoduykhanh/PowerDNS-Admin#16]
It would be nice to have a docker setup for this application similar to https://github.com/obi12341/docker-pdns, https://github.com/tuxis-ie/nsedit or https://github.com/xbgmsharp/yapdnsui/blob/master/Docker.md.

How could I assist in preparing such?

**Comment by ivanfilippov** [comment]
Hi @almereyda!

[Here is a sample initial implementation of a Dockerfile](https://github.com/ivanfilippov/PowerDNS-Admin/blob/docker/Dockerfile) that builds a docker image that just runs PowerDNS-Admin, all the parameters are configurable via variables in the Dockerfile. I'm just a beginner when it comes to Docker, so you're more than welcome to contribute to it. :smile: 

What use-case are you going for with Docker so that I can take that into consideration when working on this? I was thinking of integrating MySQL directly into the docker container but that wouldn't work for some setups (mine for example, I have a Galera cluster which hosts all my application databases, so I don't need another database in the container). I was also thinking of integrating Nginx as a reverse proxy into the container but that may be against the docker creed of one application per container.

**Comment by ngoduykhanh** [comment]
Also take a look at [docker-compose.yml)](https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/docker-compose.yml)
