### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by cropalato** [ngoduykhanh/PowerDNS-Admin#182]
Hi,

Your project is really good, I've been testing for some time and now i decide to check for new features/bug fixes.
Since there is no changelog is difficult to understand what changed since my last upgrade.
Is it possible to add a changelog?

**Comment by ivanfilippov** [comment]
Since PowerDNS-Admin doesn't have "releases" and is usually used directly from the master branch on github a changelog would be tough to maintain. For now I recommend using the github commit log to review what was changed or added. If we decide on doing "releases" then we can create a changelog to show difference from one release to the next.

The owner of the project (@ngoduykhanh) might have a different opinion, I'll keep this issue open until he comments. :)

**Comment by ngoduykhanh** [comment]
Commit history is good enough for me at the moment. Since the project is still under development and bug fixes, we don't do any "release" to have change changlog
