### ISSUE TITLE
History detail

### ISSUE THREAD

**Issue by openmsk** [ngoduykhanh/PowerDNS-Admin#184]
User deleted record 
User added record
User changed record - what value?

**Comment by openmsk** [comment]
Resolved:
```
# cat /etc/systemd/system/powerdns-admin.service 
[Unit]
Description=PowerDNS-Admin
After=network-online.target

[Service]
Type=simple
WorkingDirectory=/etc/python/flask
Environment="PATH=/etc/python/flask/bin"
ExecStart=/usr/bin/bash -c 'cd /etc/python; /usr/bin/virtualenv flask; source ./flask/bin/activate; /etc/python/flask/bin/python2 /etc/python/PowerDNS-Admin/run.py'
WorkingDirectory=/etc/python/PowerDNS-Admin
Environment="PATH=/etc/python/PowerDNS-Admin"
Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by ivanfilippov** [comment]
You can see the detail of changes by clicking the blue "Info" button on the right side. It doesn't list the previous data, but shows the current state of the domain.
![image](https://cloud.githubusercontent.com/assets/325998/24522051/8cba0cd6-154b-11e7-841e-39e59e36778d.png)

Because of how the PowerDNS API accepts updates, we have the send the full zone every time, so we'd need some logic to diff the current zone and the updated zone to show a difference between them. Patches are welcome. :)

**Comment by openmsk** [comment]
Иван, простите за затишье с моей стороны. 
но в моем случае кнопка info есть, но на большей части изменений не отображает детали. 
в дебаг консоли браузера пишет
```
Uncaught SyntaxError: Unexpected token v in JSON at position 244
    at JSON.parse (<anonymous>)
    at Object.prettyPrint (custom.js:171)
    at HTMLButtonElement.<anonymous> (history:895)
    at HTMLBodyElement.dispatch (jQuery-2.2.0.min.js:3)
    at HTMLBodyElement.r.handle (jQuery-2.2.0.min.js:3)
```
это в Chrome.
в Safari чуть иначе выглядит ошибка, но поведение такое-же

![screen shot 2017-04-11 at 17 33 50](https://cloud.githubusercontent.com/assets/3602406/24914500/11d334e8-1edd-11e7-9f2d-5881980ade44.png)

позднее, если нужно, могу посмотреть на ошибки в ИЕ, Edge, FF. Но поведение во всех браузерах одинаковое
