### ISSUE TITLE
Deploy a Slave PowerDNS server

### ISSUE THREAD

**Issue by blackyzero** [ngoduykhanh/PowerDNS-Admin#226]
Hi everyone,

What would be a proper way to deploy a Slave PowerDNS server?

I have done with Master PowerDNS server, running with MariaDB backend and PowerDNS-Admin management interface.

I'd like to have auto replication between two PowerDNS server, but very low experience on deployment/setup replication or failover DNS system.

Currently, both NS1 and NS2 are now pointing to same Ip address that i think it's not really good.

Thank you very much.

**Comment by fenice2** [comment]
I don't think your question is really suitable in this issues section as it's for the PowerDNS-Admin product not general PDNS questions. You can find plenty of information about implementing a PDNS slave on the internet or even the PDNS Documentation.

However, I'd recommend against implementing a Master/Slave setup and suggest you set-up two 'master's and point them both to the same MySQL server via the gmsyql settings. I happen to have that configuration for three PDNS server pointing to a Percona XtraDB Cluster for their DB, it works well. ;)

I can highly recommend Percona products instead of MariaDB as I find them to be more performant and less prone 'losing' the mysql server after upgrades or server restarts.
