### ISSUE TITLE
Update Possibility

### ISSUE THREAD

**Issue by Ramalama2** [ngoduykhanh/PowerDNS-Admin#341]
Hi, can we make updates possible?
The main thing is "flask db upgrade" runs into errors, i think because of my actual mysql database is already populated... or exists...

1. ive made a script that doesn't work atm... Maybe i can get some help :-)
```
#!/bin/bash
/usr/bin/systemctl stop pdns-admin
rm -rf /opt/web/powerdns-admin
git clone https://github.com/ngoduykhanh/PowerDNS-Admin.git /opt/web/powerdns-admin
cp /root/scripts/config.py /opt/web/powerdns-admin/config.py
cd /opt/web/powerdns-admin
# virtualenv -p python3 flask
# . ./flask/bin/activate
# export FLASK_APP=app/__init__.py
# flask db upgrade
# yarn install --pure-lockfile
# flask assets build
# exit
# /usr/bin/systemctl start pdns-admin
```
The commented you things dont work atm :-)

2. flask db upgrade
I dont know how to solve this... the only solution atm is deleting the database...

Cheers :-)

**Comment by Ramalama2** [comment]
I have a better idea,

It would be simpler if we make a Mysql/Bash script for:
1. exporting users/account/templates
2. delete and recreate an empty database
3. script from above to update Powerdns-Admin
4. import users/account/templates

Would be better, because ngoduykhanh doesnt need to implement any new stuff for updating...

I Just need help to get that scripts working :-)

**Comment by tmuncks** [comment]
All this stuff is handled by flask-migrate since a few months back.

If you get a new version of PowerDNS-Admin from git, there's a populated "migrations" directory included, which is responsible for all these updates. The problem is, that if your database is from before this time, your `alembic_version` probably don't match anything - or doesn't exist at all, which will cause problems on update.

Try:
```
select * from alembic_version;
```
Your version should be: 787bdba9e147

The problem with your suggestion to create scripts to do something that actually already works (perhaps the docs need updating), is that it's going to be pretty hard to maintain. Every time there's a schema change, instead of relying on the flask-migrate stuff to automatically facilitate upgrade/downgrade of the scheme directly from flask, on all supported databases, the scripts would have to be modified and tested on all types of databases, to no real benefit.

If you are fairly sure your database is running the latest schema, try "stamping" your database version (after making sure you have a fresh backup of it!):
```
flask db stamp 787bdba9e147
```

After that, running:
```
flask db upgrade
```
Should just complete without error (and without making any changes to the database).

**Comment by ntinti** [comment]
An update instruction would be more than usefull... Also information which versions are major for upgrading...

**Comment by ngoduykhanh** [comment]
I agree with @tmuncks . 
@Ramalama2 we should fix the migration scripts if there are errors.
@ntinti We have never made a release. Still trying to have most table version to tag the first release ...let's say v0.01?

**Comment by Ramalama2** [comment]
The actual version with Commit 542 is im my eyes really good, i dont have any errors. Really you work is awesome.
Im just trying to figure out how i can do a update script :-)

About the db, thats good, so we dont need anything special here.
I just had that problem because ive tested the script and updated the same version 4 times...

To Anyone:
Does anyone have a solution to get virtualenv working in my bash script above? :-)

Cheers :-)

**Comment by Ramalama2** [comment]
If i find a way i will post here, but for the moment, im Closing this...
