### ISSUE TITLE
Master-Slave configuration issues

### ISSUE THREAD

**Issue by m1911** [ngoduykhanh/PowerDNS-Admin#370]
Must the master/slave server have Powerdns-admin installed?

**Comment by tmuncks** [comment]
As long as the master server API port can be reached from PowerDNS-Admin, you should be fine. They don't have to be the same server.

**Comment by m1911** [comment]
@tmuncks 
Thank you for your answer.
I would like to ask the main server installed Powerdns-admin, from the server also need to install powerdns-admin?

**Comment by fenice2** [comment]
You can install Powerdns-admin on any server in your network, it doesn't have to be on the PDNS server itself. Does that answer your question or have I misunderstood it?

**Comment by m1911** [comment]
@fenice2 
Powerdns master and slave How to configure?

**Comment by fenice2** [comment]
That's now a question for here, it's already been described in the PowerDNS documentation and there's a ton of articles on the internet that cover this. Take a look at this search: https://preview.tinyurl.com/pdns-slave

I don't think a maste/slave is the best answer, I p[refer to use a percona cluster/proxysql/keepalived config to give me a HA solution. The cluster get's updated by one of the server and all the other PDNS servers just read that percona cluster DB.

**Comment by m1911** [comment]
@fenice2 
Thanks, I'll keep looking on the Internet.

**Comment by Ramalama2** [comment]
Just an tip how i do this:

I have a Mysql Galera Cluster (with 3 Servers)
On every of them runs pdns-auth + pdns-rec + powerdns-admin.
Everything of them uses the same Mysql Database (Galera Cluster)

And its working perfect here.

It doesnt matter on which of the servers i use Powerdns-admin, because of the synced database...
Just with the Avatars (the upload folder in powerdns-admin) i have to sync myself... but for that case i use incrond with a script...

Cheers :-)

**Comment by m1911** [comment]
@Ramalama2 
Thank you for your answer.
I have used Powerdns's supermaster function to solve the master-slave.

**Comment by Ramalama2** [comment]
i understand, but for me it seems like the mysql galera cluster configuration is superrior to everything...
you dont need to check if you domain is a master or slave or native domain or if there is any bug with the master/slave configuration etc etc....
+ If you change on Server1 sth, you get instantly the change on server2 too...
(Dunno how fast this is with a normal master-slave configuration)

The only negative sideeffect is, that its recommend to use at least 3 servers for Galera-Cluster....
Will work with 2 too, but its not recommended...
However, your 3rd server can be a VM, which runs only mysql and nothing else...

Im just asking, because im myself fascinated how awesome this configuration works :-)

Cheers :-)

**Comment by fenice2** [comment]
@Ramalama2 @m1911 

That scenario works well with Galera cluster and I use 5 VMs for my galera DBs and anything less than three servers is not a cluster. As I mentioned earlier, I also use proxysql and keepalived to provide redundancy in case any of the DB servers go down and you'll only need one IP address for your MySQL PowerDNS DB with that config.

I'd also recommend you use Precona XtraDB for the cluster, I've always had problems with MariaDB and some of the servers failing or refusing to start and/or corrupted DBs in recent versions of MariaDB. Percona is as performant and the product values data consistency for the DBs.
