### ISSUE TITLE
DNSSEC not able to enable

### ISSUE THREAD

**Issue by Oratorian** [ngoduykhanh/PowerDNS-Admin#389]
How do i enabled dnssec in the docker-compose executed pdns-server docker image?

**Comment by rkerr** [comment]
The container docker-compose uses seems to have dnssec disabled by default. I've put an issue in upstream to see if they'd consider enabling it - psi-4ward/docker-powerdns#18

Otherwise you would need to change the pdns.conf file in the container. First do `docker ps --filter "name=pdns-server"` to get the conainer ID then `docker exec -it containerid /bin/sh` to enter the container, finally use vi to change /etc/pdns/pdns.conf to include gmysql-dnssec=yes

**Comment by Oratorian** [comment]
I already did that, but the pdns.conf seems to be overwritten in each Container restart. 

What really helped was adding the --gmysql-dnssec=yes to the docker-compose.yml as startup parameter to the container options.

**Comment by psi-4ward** [comment]
pdns.conf sould not get overwritten

**Comment by Oratorian** [comment]
But it is, every time my system issues a restart cause of system updates, the pdns.conf inside the container is back to standard.

I tried to mount /etc/pdns/conf.d as volume to create own configs there but I could not figure it out yet how to do that.

Can you give a small example on how I would need to do that @psi-4ward

**Comment by psi-4ward** [comment]
Did you solve your problem?
