### ISSUE TITLE
The server refused to process your request and return a 400 error. You may return to the dashboard.

### ISSUE THREAD

**Issue by jpenberthy** [ngoduykhanh/PowerDNS-Admin#425]
When trying to add a domain already there is should give a better error then: "The server refused to process your request and return a 400 error. You may return to the dashboard."

**Comment by ozid** [comment]
Check /var/log/syslog
I had the same problem and it was due to missing tables in database.
I had to re-create tables

Also go to the webserver: admin/setting/pdns
and set the correct version of pdns for API, you can check it directly on your server:
`pdns_control version`

Double check pdns.conf for correct database settings
