### ISSUE TITLE
When domain is deleted outside of PowerDNS-Admin the worker timeouts on dashboard

### ISSUE THREAD

**Issue by prupert** [ngoduykhanh/PowerDNS-Admin#428]
When a PowerDNS domain is deleted outside of PowerDNS-Admin, i.e. in the PowerDNS back-end directly, the PowerDNS-Admin gunicorn worker times out (already tried raising the limit) on the /dashboard page:

```
Dec 19 13:49:49 dns gunicorn: [DEBUG] Update domains in foreground
Dec 19 13:49:49 dns gunicorn: [DEBUG] Starting new HTTP connection (1): 127.0.0.1:8081
Dec 19 13:49:49 dns gunicorn: [DEBUG] http://127.0.0.1:8081 "GET /api/v1/servers/localhost/zones HTTP/1.1" 200 2
Dec 19 13:51:20 dns gunicorn: [2018-12-19 13:51:20 +0100] [18743] [CRITICAL] WORKER TIMEOUT (pid:18829)
Dec 19 13:51:20 dns gunicorn: [2018-12-19 13:51:20 +0100] [18829] [INFO] Worker exiting (pid: 18829)
Dec 19 13:51:20 dns gunicorn: [2018-12-19 13:51:20 +0100] [21424] [INFO] Booting worker with pid: 21424
```

Removing the domains also from the `domains` table in the PowerDNS-Admin MySQL database resolves the issue. 

It seems that this is a bug in PowerDNS-Admin which renders PowerDNS-Admin unusable if a domain is deleted on the PowerDNS nameserver.

**Comment by ngoduykhanh** [comment]
Hmm, I tried to reproduce this issue but i couldn't. I am wondering how can this happen because we already have the code for removing the old domain in PDA's database to sync the list of domain between 2 databases. See https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/app/models.py#L836

**Comment by prupert** [comment]
275

**Comment by ngoduykhanh** [comment]
There is a for loop on the list of those domains to remove the domain owner, setting before completely remove the domain name from the database. It might slow with that number of domain. You might want to increase the gunicorn timeout config to avoid the issue.

**Comment by prupert** [comment]
Already did. From 30 to 90.

**Comment by eht16** [comment]
Probably this issue is the same as #541.

I've got bitten by this as well and I'm able to reproduce it:
for debugging, I set up a local PDNS server with about 55000 domains.
The initial sync took some time as expected.
Further sync attempts run in a few seconds (most time is reading the zones from PDNS).
BUT once a domain is deleted in PDNS and so the sync tries to delete the domain also in the PowerDNS-Admin database, it executes single `SELECT` queries for each domain in the database.
No idea why this happens, it is related to `Domain.query.filter(Domain.name == domain_name).delete()` which triggers the many queries.
The following diff workarounds the problem:
```diff
diff --git a/powerdnsadmin/models/domain.py b/powerdnsadmin/models/domain.py
index 53a122a..1aa42d8 100644
--- a/powerdnsadmin/models/domain.py
+++ b/powerdnsadmin/models/domain.py
@@ -517,7 +517,7 @@ class Domain(db.Model):
         db.session.commit()
 
         # then remove domain
-        Domain.query.filter(Domain.name == domain_name).delete()
+        db.session.delete(domain)
         db.session.commit()
         current_app.logger.info(
             "Deleted Domain successfully from pdnsADMIN: {}".format(
```
Though I'm not yet sure why the original code issues `SELECT` statements for each domain in the database. My best guess so far is that there is something wrong with the relations in the SqlAlchemy model.
The above change should have the same effect: `DELETE FROM domain where id = XX`. Still it feels just as a workaround unless the underlying problem is clear.


And then there is one more problem:
in the second half of the sync code when iterating over the previously fetched domains to add/update, SqlAlchemy issues a `SELECT` statement again for the current domain while iterating.
This does only happen if at least one domain has been deleted before. If no domain was deleted, then no additional `SELECT`queries are issued.
I assume this happens because SqlAlchemy thinks the previously fetched domains from the database are dirty or outdated because in the same table deletions happened.

**Comment by eht16** [comment]
I finally found a better way: using a single database transaction solves all of the above described problems: with a single transaction SqlAlchemy doesn't need to re-fetch all the objects after any modification. This heavily speeds up the whole update process for my test case with 55000 domains.
See #655 for details.
