### ISSUE TITLE
Apply Changes does not invoke refresh on PDNS itself

### ISSUE THREAD

**Issue by zimmertr** [ngoduykhanh/PowerDNS-Admin#475]
Hello, I am not sure if this is an issue or an intended feature. However, I was not able to determine the proper method to obtain support for this software so I thought I would create an issue here.

After much troubleshooting last night I discovered that `Apply Changes` in PowerDNS-Admin only saves the records to my backing MySQL Database. It does not, however, refresh the records that PowerDNS can resolve. Which does not come into effect until I manually SSH into the server and run a `systemctl restart pdns-recursor`.

The sort of defeats the point of managing DNS through a web interface. Am I looking at this the wrong way? Have I configured something incorrectly? Is it possible to trigger a refresh or reload action for PowerDNS from PowerDNS-Admin?

**Comment by ngoduykhanh** [comment]
If you can see the new record data in pdns database after applying changes, it means the PDA works normally.

PDA itself doesn't take care of restarting pdns service, and I don't see any reason to do that. Your problem might be related to the local resolver or a bug in pdns itself.

**Comment by zimmertr** [comment]
Can you confirm for me that it is at least necessary to restart pdns-recursor in order to resolve newly added records so I can know if this is an intended feature or configuration problem?

**Comment by ngoduykhanh** [comment]
PDA is an UI for the PowerDNS authoritative server, the communication is via API only. We don't take care of restarting the recursor service. I think there is some issue with your setup :-)

**Comment by zimmertr** [comment]
I understand that PDA does not take care of restarting the recursor service. I'm asking if it is necessary to restart the recursor service when making record updates from PDNS. Regardless if one is using PDA or not.

**Comment by p53** [comment]
that's the question to PDNS not PowerDNS-Admin, but as i checked in PDNS RECURSOR you can configure domains which you forward to PDNS AUTHORITATIVE SERVER only in config file so i assume also from this mail communication that you need to restart recursor every time you add new zone to PDNS, hmm would be great if that could be done through API also...

**Comment by zimmertr** [comment]
Well for what it's worth I created a new record today and it automatically started resolving without restarting the recursor... No idea why it works inconsistently.

**Comment by ieaster1** [comment]
I came here for a similar question on my mind of if PowerDNS Admin will invoke a Recusor restart or clear the cache.

As my understanding, depending on your setup, the Recursor is going to cache the DNS requests for faster response times.  If you update that record, the Recursor won't immediately update the cache.  You need to either wipe it or restart the Recursor.

Since PDA is primarily set to interact with the Authoritative Server, is there no intention to allow Recursor cache clearing after changing or adding new records?

**Comment by MelwinKfr** [comment]
I also think it would be great if PowerDNS-Admin integrates this feature. Especially since the recursor component is now mandatory in any PDNS system. An alternative solution would be to develop a hook per zone.

The win win situation I imagine would be calling [this command](https://doc.powerdns.com/recursor/manpages/rec_control.1.html) from a custom shell script executed by PowerDNS-Admin after a modification is made in a given zone. Is it something you would consider?

**Comment by johnwc** [comment]
We too have this issue, where we must go into the PDNS server and run `rec_control` to clear the cache, in order for the newly created record to be resolved immediately. Else we just wait 15 minutes or so and it refreshes itself. It would be nice if there was an option in PDA to enable it to call the [flush cache API](https://doc.powerdns.com/recursor/http-api/endpoint-cache.html) for the resolver upon applying any record changes.
