### ISSUE TITLE
Unable to logout

### ISSUE THREAD

**Issue by reissmann** [ngoduykhanh/PowerDNS-Admin#517]
I am unable to logout from the UI, when running PowerDNS-Admin 
- as systemd service (as described here: https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Systemd-example) with an Apache2.4 reverse proxy 
- as apache wsgi application (as described here: https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/WSGI-Apache-example)

When accessing port 9191 directly from a webbrowser, logout works.

To be more specific: When clicking the logout button, the site reloads, but I am still logged in.

Do I miss something?

**Comment by ngoduykhanh** [comment]
It is a matter of the Apache reverse proxy configuration I believe. I haven't tried with that sample config, but the Nginx one works for fine me.
https://github.com/ngoduykhanh/PowerDNS-Admin/wiki/Running-PowerDNS-Admin-with-Systemd,-Gunicorn--and--Nginx

**Comment by madmath03** [comment]
I also encountered this behavior with a different setup.

In my case, the reverse proxy was handling SSL connection while pdns-admin was dockerized ([custom docker container](https://github.com/Monogramm/docker-powerdns-admin)).
I had several error messages due to mixed content (resources retrieved by HTTP while connection is HTTPS). When trying to logout, the Service Worker was complaining that it was sitting behind a reverse proxy and redirecting instead of logging out.

I "_solved_" this by making gunicorn use SSL (set certfile and keyfile) and unregistering the Service Worker (forcing it to update itself).
Hope that can help.
