### ISSUE TITLE
Emails with the .network tld are not valid

### ISSUE THREAD

**Issue by YanTHIERY** [ngoduykhanh/PowerDNS-Admin#589]
Hi everyone,

**Problem :**
I'm trying to use PowerDNS admin for test purpose.
When i try to an account, the [_.network_](https://icannwiki.org/.network) top level domain is not recognized as a valid email address.

**How to reproduce**
In the webui, create an account with _.network_ top level domain in the email address

**Comment by breard-r** [comment]
The problem seems to be located in [app/templates/register.html](https://github.com/ngoduykhanh/PowerDNS-Admin/blob/0b2eb0fbf8ef59a4dcc392863f6f344f7e192f2c/app/templates/register.html#L47-L48) where a non-compliant regex is used to validate the email on the client's side. The correct solution would be to [remove this regex](https://davidcel.is/posts/stop-validating-email-addresses-with-regex/).

**Comment by ngoduykhanh** [comment]
For now, PDA doesn't have any feature to deal with the email sending so we can't validate the user's email address in that way so I keep that regex validation method. Feel free to remove/adjust it for your case.

**Comment by splog123** [comment]
Can we then ship a regex that works? This:

((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$

no longer fully works since top level domains were opened up for purchase. Email addresses of the form

spolg@abc 

are becoming more common and this will increase, not decrease, in future. I don't think it's fair to expect admins to maintain this regex which gets overwritten with every git pull

**Comment by ngoduykhanh** [comment]
I see,

It doesn't make sense for admins to keep maintain a different regex while the original one is under version control unless we have flexibility to adjust it via config file or DB. But it is overkill, I haven't ever seen any implementation like that.

What about:
- Completely disable the email validation using regex (or just keep it simple with '@' validation only)
- Implement SMTP feature, allow us to ask for email confirmation after registration.

**Comment by splog123** [comment]
I like your suggestion but  would tweak it just slightly, adding a config option for EMAIL_VERIFICATION with values "simple" or "strict"

simple:
- regex that checks for "@" or possibly ".*@[a-z0-9\.-]"

strict:
- regex that checks for "@" or possibly ".*@[a-z0-9\.-]"
-  Implement SMTP feature, allow us to ask for email confirmation after registration.

In my case I would have to select simple as my PDNSA hosts cannot receive mail at all so the verification cannot complete. This is common in corporate setups so I use support tickets requesting access instead.

**Comment by ngoduykhanh** [comment]
Sure. We need flexibility in choosing those settings.
Btw, Regarding SNMP, it is for sending email from PDA, not for receiving email

**Comment by breard-r** [comment]
> Can we then ship a regex that works?

I think that's a bad idea, and I seriously recommend to simply remove the regex. The input has the email type, which means that [the browser already checks whether or not the email format is correct](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email). Therefore, please stop trying to re-validate it a second time with a broken pattern.

**Comment by ngoduykhanh** [comment]
I made a PR for this. Hope it help!

**Comment by breard-r** [comment]
That's a great news, thank you! :)
