### ISSUE TITLE
Can't connect to MySQL server

### ISSUE THREAD

**Issue by gnanasankar** [ngoduykhanh/PowerDNS-Admin#805]
powerdns_admin | sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (2002, "Can't connect to MySQL server on '127.0.0.1' (115)")

But my docker-compose.yml if fine..

SQLALCHEMY_DATABASE_URI=mysql://poweradmin:powerdns@127.0.0.1:3306/powerdns

Please help me to short out this issue

**Comment by MrGeneration** [comment]
Please think of a docker container a similar way like a virtual machine. 
Thus, if you tell your container to look at localhost, it will look inside the container, not on your containers host.

You have to know the hosts IP address in your container context.
This usually is easier if you have a static IP setup.

For example my docker-compose file:
``
`version: '3'
services:
    pdns-admin:
       image: ngoduykhanh/powerdns-admin:latest
       container_name: powerdns_admin
       restart: always
       networks:
           pdns-net:
             ipv4_address: 172.16.16.14
       ports:
          - "127.0.0.1:9191:80"
       logging:
         driver: json-file
         options:
            max-size: 50m
       environment:
          - SQLALCHEMY_DATABASE_URI=mysql://user:password@172.16.16.1/pdns
          - GUINCORN_TIMEOUT=60
          - GUNICORN_WORKERS=2
          - GUNICORN_LOGLEVEL=DEBUG
networks:
   pdns-net:
      driver: bridge
      ipam:
         driver: default
         config:
           - subnet: 172.16.16.0/24
```

Logically I did remove sensitive information, so you'll need to adjust this.

**Comment by gnanasankar** [comment]
After enabled with host static ip now it through's the below error..

sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1045, "Access denied for user 'root'@'172.18.0.2' (using password: YES)")

**Comment by MrGeneration** [comment]
You're using a wrong password for root. 🤷‍♂️

**Comment by gnanasankar** [comment]
ok will check...

# docker-compose up -d
ERROR: stat /var/lib/docker/overlay2/f495871cff26c383c50dbfd2b5cff23e66049fa37d3dbd8f927c3ffd3c04a552: no such file or directory

how to fix this issue...No data in it..

# pwd
/var/lib/docker/overlay2
# ll
total 4
drwx------ 2 root root 4096 Aug 13 19:54 l

**Comment by gnanasankar** [comment]
No password is fine.I can able to directly login to root from terminal with same password..

**Comment by gnanasankar** [comment]
Mysql issue has been fixed and now i have below issue while add new domain..please help me

**Comment by JulianHi** [comment]
just some help for someone with the same problem:

First, you need to use the host IP instead of localhost or 127.0.0.1. Under Windows / Mac you can also use "host.docker.internal" under Linux this is not supported yet. (at least with my docker version) 

For me: "ip addr show docker0" showed my docker host ip. In my case it was "172.17.0.1". I used this ip address to connect to mysql, but my connection still failed with "Can't connect to MySQL server on "

By default many mysql server like mariaDB limits the access to 127.0.0.1. So you need to change the configuration of your mysql server and allow access also from your docker host ip. In my case (mariaDB) the mysql service only allowes one ip address. Alternativ you can bind to 0.0.0.0 or uncomment "bind-address" and add "skip-networking=0" and "skip-bind-address" to the end of the configuration.

After this my docker container was able to connect to my mysql server. I recommend to use a firewall to restrict the access to port 3306 from the outside world.

Hope this might help someone to find the problem more fast.
