### ISSUE TITLE
[API] some change proposals to be usable by terraform powerdns provider with user api key. (feature request)

### ISSUE THREAD

**Issue by WhatshallIbreaktoday** [ngoduykhanh/PowerDNS-Admin#844]
Hello, 

Played a little bit with powerdns-admin and terraform powerdns provider ([https://github.com/terraform-providers/terraform-provider-powerdns]).

I was thinking on the following use-case (allowing other teams to automate without giving them Admin api key) : 
- distribute Api-keys to other teams (with limitied user rights)...
- Create the zones myself (with admin rights)...
- allow other teams to use terraform powerdns provider with their user api key to register their records themselves. (obviously zone creation will not work for them in this case).

Powerdns terraform Provider first requests : api/v1/servers/   and api/v1/servers/<server_id>  to retrieve Powerdns version and API versions...
So my proposal is to change API routes to let User API keys make this API calls, with of course letting only admins change zones...
But I have some doubts about this :  
Is it feasible without creating some security breach?  (I'm not so familiar with python applications).

One more thing : Terraform Powerdns Provider allows to  put trailing dot in zone name.. which is not allowed in the apikey_can_access_domain function  => adding .rstrip(".") when retrieving zone_id solves the issue and passes the requests correctly to powerdns. 

Great work anyway and have a nice day.

**Comment by jbe-dw** [comment]
Hello,

I tested it weeks ago and came accross the same issue. You need an admin role to access the cited endpoints. This point is crucial. It would be so nice to fix it quickly because here at DW we deploy PowerDNS because of its API, but PDNS team doesn't want to manage RBAC so we need a frontend API to manage it.

I am deploying PowerDNS Admin and the improvments on API in the latest release is a good point. But with this permission issue, right now I have to install another bit of software to filter out API calls that is compatible with terraform.

I guess your project would be more famous if you can brand that it provides a PowerDNS Api frontend with RBAC control compatible with terraform PowerDNS Provider.

Thank you, i'm interested in it. I may do a PR but I'm quite busy to dive into your code now.
