### ISSUE TITLE
No MX Priority Setting

### ISSUE THREAD

**Issue by techhelper1** [ngoduykhanh/PowerDNS-Admin#90]
I'm seeing the records are getting added with a static priority of 10, which is wrong. The priority needs to be user setable.

I will preface this with the fact that I have not installed this to give it a fair review, but I found this issue by looking through the source code and the screenshots.

**Comment by ngoduykhanh** [comment]
The priority field has been removed from PowerDNS API since version 3.4.2 (see [change log](https://doc.powerdns.com/md/changelog/)).

But, we did support to set the priority of **MX** records, follow the API data format [here](https://doc.powerdns.com/md/types/#mx).
<img width="600" alt="screen shot 2016-07-18 at 4 54 16 pm" src="https://cloud.githubusercontent.com/assets/6447444/16911419/8aea8ed2-4d08-11e6-990b-a79454c2b91f.png">
