### ISSUE TITLE
Slow with many Domains

### ISSUE THREAD

**Issue by righter1983** [ngoduykhanh/PowerDNS-Admin#93]
Hi first of all great work, was looking for that since years...

On one of my servers which is managing 1600 domains with 11'000 records, The dashboard needs 10 seconds to load (Corei7 with SSD).

Do you have some tips to tweak it?

**Comment by ngoduykhanh** [comment]
I haven't tried with that amount of domain yet. But the probably reason is because we are fetching the pdns API every time we load the dashboard to sync the domain metadata to local PowerDNS-Admin (And the DNSSEC checking part also) - see [this function](https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/app/models.py#L492). Disabling this feature and replace by another method can speed up the Dashboard a lot, at least in your case ;).

**Comment by righter1983** [comment]
Ok thanks for your help.
Cool would be a limit for the dashboard. So that it will only load a configurable amount of zones. and if you click on next page, it loads the details only then for the next amount of zones. :-)

**Comment by psy0rz** [comment]
so this issue isnt realy fixed and shouldn't be closed? it seems powerdns-admin still is inefficient with many domains.

it downloads a list of ALL the domains to the browser, so this is not scalable!

**Comment by paradoxni** [comment]
4000 domains here. The dashboard is so slow on each load it makes the whole thing practically unusable.

**Comment by fabiorauber** [comment]
This solved for me https://github.com/ngoduykhanh/PowerDNS-Admin/pull/207

**Comment by psy0rz** [comment]
thanks :D
