### ISSUE TITLE
Issue with add record field when sort order changed

### ISSUE THREAD

**Issue by trenb** [ngoduykhanh/PowerDNS-Admin#94]
When adding a record to a domain, if you change the sort order "highest to lowest", the entry dialogue is moved to the bottom of the list. Changing the sort order should not change where the entry dialogue is located.

Let me know if you need any more information.

**Comment by jallakim** [comment]
Somewhat related (not sure if it should have it's own issue, but the solution should probably address both issues as "one");

If you're filtering records (e.g. searching for 'dns'), and you hit "Add Record", the entry dialogue isn't shown at all (since it doesn't match 'dns'). You have to clear the filter in order to see the dialogue.
