### ISSUE TITLE
400 Bad Request when adding domain

### ISSUE THREAD

**Issue by potvinp** [ngoduykhanh/PowerDNS-Admin#975]
Receiving Error 400: Bad Request wehen trying to add a domain.

Logs show the following when trying to add a domain using docker container. Note the host can ping the system running powerdns perfectly fine. 
```
[2021-07-11 01:11:28,328] [domain.py:252] ERROR - Cannot add domain domain.com. HTTPConnectionPool(host='xxx.xxx.xxx.xxx', port=8081): Max retries exceeded with url: /api/v1/servers/localhost/zones (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb7a66ba1c0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
```

**Comment by yokiyoki22** [comment]
Please give us some more insight on your setup:

- Is the API enabled?
- Is the pdns webserver listening on the correct address?
- Is the firewall blocking the connection?
- Is everything else working as expected?

**Comment by danielbrunt57** [comment]
I have battled this for several hours now.
Is the API enabled? - Yes, curl commands work.
Is the pdns webserver listening on the correct address? - Yes.
Is the firewall blocking the connection? - No.
Is everything else working as expected? - No.

I have discovered that it is a docker issue.  My PowerDNS-Admin is running as a docker container which cannot access 192.168.1.103 which is my docker host and where pdns is.  If I add `--network host` to the docker run command and access PowerDNS-admin via port 80 (since `-p 9191:80` is null and void when using `--network host`), everything works as expected.

**Comment by danielbrunt57** [comment]
Final solution:
```
docker run -d \
  --name powerdns \
  --restart unless-stopped \
  --add-host=host.docker.internal:host-gateway \
  -e SECRET_KEY='Ka4w9SqLf]Zcq+U' \
  -v pda-data:/data \
  -p 9191:80 \
  ngoduykhanh/powerdns-admin:latest
```
pdns.conf:
```
webserver-allow-from=127.0.0.1/32,172.16.0.0/12,192.168.1.0/24
```
PowerDNS-Admin:
PDNS API URL: `http://host.docker.internal:8081`
